server:
  port: 8088
spring:
  profiles:
    active: dev


#person:
#  birthday: 2018/12/12
#  age: 18
#  kvs: {gender: F, addr: shanxisheng}
#  likes:
#    - girl
#    - boy
#    - children
#  dog:
#    color: black
#    ownerName: kerwin
#  last-name: zhangsan



---


server:
  port: 8087
spring:
  profiles: dev



---

server:
  port: 8086
spring:
  profiles: prod