server:
  port: 3344

spring:
  application:
    name: microservice-cloud-config-name  # 唯一
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kerwin1991/microservice-cloud-config.git

